version: '2'
services:
  web:
    image: luis/nodejs-ubuntu
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: dev
      PORT: 3000
      YAMMER_CLIENT_ID: xlQr8noWqA7C202b2YC2JA
      YAMMER_REDIRECT_URI: http://localhost:3000/access/yammer
    volumes:
      - ./:/var/www
    command: npm start
