version: '2'
services:
  rever-dashboard:
    image: 828489534757.dkr.ecr.us-east-1.amazonaws.com/${IMAGE_NAME}:${IMAGE_TAG}
    ports:
      - "80"
    cpu_shares: 1
    mem_limit: 131072000
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - API_URL=${API_URL}
      - MIXPANEL_TOKEN=${MIXPANEL_TOKEN}
      - INTERCOM_TOKEN=${INTERCOM_TOKEN}
      - PORT=80
      - YAMMER_CLIENT_ID=${YAMMER_CLIENT_ID}
      - YAMMER_REDIRECT_URI=${YAMMER_REDIRECT_URI}
      - APPLICATION_URL=${APPLICATION_URL}
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-1
        awslogs-group: rever-dashboard-${ENVIRONMENT}
        awslogs-stream-prefix: rever-dashboard
